apiVersion: v1
kind: Service
metadata:
  name: jupyter-lab-service
  namespace: jupyter-ml
spec:
  type: NodePort
  selector:
    app: jupyter-lab
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30088
